api: makeconfig
version: beta/1
metadata:
  name: mc
  description: "A long sentence..."
specs:
  template:
    file: ./sample/sample.template
  parameters:
    # type: Url
    # host: localhost:3000
    # path: /my-config/1031
    type: File
    path: ./sample/sample.params
    create: ./sample/sample.params-script
    env:
    - name: HAS_THIS
      default: "true"
  template-out:
    file: sample.out
  build-script:
    file: ./sample/sample.build-script
    env:
    - name: ENVIRONMENT
      default: stg
      options:
      - value: stg
      - value: prod
  post-script:
    file: ./sample/sample.post-script
  deploy-script:
    file: ./sample/sample.deploy-script